import { useEffect, useState } from 'react';

import { fetchPaymentIntent, formatCurrency } from '../../api/orderingApi';
import type { PaymentIntent } from '../../types';

interface PaymentQrProps {
  /** The CONFIRMED order to collect payment for. */
  orderId: number;
}

/**
 * Demo payment QR shown under the cart once an order is confirmed, which
 * flips to a "Payment received" confirmation after a configurable delay.
 *
 * ⚠️ DEMO ONLY — the QR is generated by kiosk-core from a deliberately
 * non-routable payee handle (see configs/ordering/payment.yaml), so scanning
 * it with a real payment app cannot move money. Nothing is charged and
 * nothing is verified: the "payment received" state is a timer, driven by
 * `simulated_success_after_seconds` from the backend so the demo can show the
 * full order → pay → done journey without a payment gateway.
 *
 * Fetches exactly once per `orderId` rather than on the cart's 2 s poll
 * cadence: a confirmed order is frozen, so its amount and QR can never
 * change, and re-fetching would only add load and make the image flicker.
 *
 * Renders nothing at all when the intent is unavailable (payment feature
 * disabled, order not confirmed, or backend unreachable) so a payment
 * problem can never hide the customer's confirmed receipt.
 */
export function PaymentQr({ orderId }: PaymentQrProps) {
  const [intent, setIntent] = useState<PaymentIntent | null>(null);
  const [paid, setPaid] = useState(false);

  useEffect(() => {
    let cancelled = false;
    // Clear immediately so a previous order's QR (or its "paid" state) is
    // never shown against a new order id while the new fetch is in flight.
    setIntent(null);
    setPaid(false);
    void fetchPaymentIntent(orderId).then((data) => {
      if (!cancelled) setIntent(data);
    });
    return () => {
      cancelled = true;
    };
  }, [orderId]);

  // Simulated settlement. Starts only once the QR is actually on screen, so
  // the customer always sees the code before it resolves — a timer started at
  // fetch time could otherwise elapse during a slow request and flash straight
  // to "paid". A delay of 0 disables the simulation entirely.
  useEffect(() => {
    if (!intent || intent.simulated_success_after_seconds <= 0) return;
    const timerId = window.setTimeout(
      () => setPaid(true),
      intent.simulated_success_after_seconds * 1000,
    );
    return () => window.clearTimeout(timerId);
  }, [intent]);

  if (!intent) return null;

  const demoBadge = intent.is_demo ? (
    <p className="mt-2 rounded-md bg-amber-100 px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-amber-800">
      {intent.demo_banner}
    </p>
  ) : null;

  if (paid) {
    return (
      <section
        className="mt-4 rounded-lg border border-green-200 bg-green-50 p-4 text-center"
        aria-live="polite"
      >
        <div className="text-3xl leading-none">✅</div>
        <p className="mt-1 text-sm font-bold text-green-800">{intent.success_message}</p>
        <p className="mt-1 text-lg font-bold text-green-700">{formatCurrency(intent.amount)}</p>
        <p className="text-[11px] text-green-700/80">
          {intent.payee_name} · {intent.order_ref}
        </p>
        {demoBadge}
      </section>
    );
  }

  return (
    <section
      className="mt-4 rounded-lg border border-gray-200 bg-white p-3 text-center"
      aria-label="Payment QR code"
    >
      <h3 className="text-xs font-semibold uppercase tracking-wide text-gray-500">Scan to Pay</h3>

      <div className="mt-2 flex justify-center">
        <img
          src={intent.qr_svg_data_uri}
          alt={`Payment QR code for order ${intent.order_ref}`}
          width={intent.qr_size_px}
          height={intent.qr_size_px}
          style={{ width: intent.qr_size_px, height: intent.qr_size_px }}
          className="rounded border border-gray-200 bg-white p-1"
        />
      </div>

      <p className="mt-2 text-lg font-bold text-intel-blue">{formatCurrency(intent.amount)}</p>
      <p className="text-[11px] text-gray-500">
        {intent.payee_name} · {intent.order_ref}
      </p>

      {demoBadge}
    </section>
  );
}

export default PaymentQr;
